import{a as q,S as v,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="51729015-e356512e01098e6cfb5d1c735",$="https://pixabay.com/api/",B=15;async function d(t,r){const s={key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:B};return(await q.get($,{params:s})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){const r=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:o,views:i,comments:E,downloads:b})=>`
 <li>
 <a href="${n}">
 <img src="${s}" alt="${e}" />
 </a>
 <div class="info">
 <p>Likes: ${o}</p>
 <p>Views: ${i}</p>
 <p>Comments: ${E}</p>
 <p>Downloads: ${b}</p>
 </div>
 </li>
 `).join("");m.insertAdjacentHTML("beforeend",r),M.refresh()}function A(){m.innerHTML=""}function h(){f.classList.remove("hidden")}function p(){f.classList.add("hidden")}function L(){y.classList.remove("hidden")}function S(){y.classList.add("hidden")}const w=document.querySelector(".form"),C=document.querySelector(".load-more");let c=1,u="",l=0;w.addEventListener("submit",I);C.addEventListener("click",O);async function I(t){t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(!r){a.error({title:"Error",message:"Please enter a search query!"});return}u=r,c=1,A(),S(),h();try{const s=await d(u,c),{hits:n,totalHits:e}=s;if(l=e,n.length===0){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}a.success({title:"Success",message:`We found ${l} images.`}),g(n),document.querySelectorAll(".gallery li").length<l?L():a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})}catch(s){a.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(s)}finally{p(),w.reset()}}async function O(){c+=1,h(),S();try{const t=await d(u,c),{hits:r}=t;g(r),document.querySelectorAll(".gallery li").length<l?L():a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}),x()}catch(t){a.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(t)}finally{p()}}function x(){const t=document.querySelector(".gallery li");if(!t)return;const{height:r}=t.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
