import{a as b,S as w,i}from"./assets/vendor-BK_rxH-O.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const E="51729015-e356512e01098e6cfb5d1c735",v="https://pixabay.com/api/",q=15;async function P(r,t){const n={key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:q};return(await b.get(v,{params:n})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new w(".gallery a",{captionsData:"alt",captionDelay:250});function M(r){const t=r.map(({webformatURL:n,largeImageURL:s,tags:e,likes:o,views:a,comments:L,downloads:S})=>`
      <li>
        <a href="${s}">
          <img src="${n}" alt="${e}" />
        </a>
        <div class="info">
          <p>Likes: ${o}</p>
          <p>Views: ${a}</p>
          <p>Comments: ${L}</p>
          <p>Downloads: ${S}</p>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function $(){f.innerHTML=""}function x(){m.classList.remove("hidden")}function I(){m.classList.add("hidden")}function O(){y.classList.remove("hidden")}function h(){y.classList.add("hidden")}const u=document.querySelector(".form"),l=document.createElement("button");l.type="button";l.className="load-more hidden";l.textContent="Load More";document.querySelector("main").appendChild(l);let c=1,p="",d=0;u.addEventListener("submit",A);l.addEventListener("click",C);async function A(r){r.preventDefault();const t=r.target.elements["search-text"].value.trim();if(!t){i.error({title:"Error",message:"Please enter a search query!"});return}p=t,c=1,$(),h(),await g()}async function C(){c+=1,await g(!0)}async function g(r=!1){try{x();const t=await P(p,c),{hits:n,totalHits:s}=t;if(c===1){if(d=s,n.length===0){i.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}),u.reset();return}i.success({title:"Success",message:`We found ${d} images.`})}M(n),u.reset(),c*15<d?O():(h(),r&&i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})),r&&H()}catch(t){i.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(t)}finally{I()}}function H(){const r=document.querySelector(".gallery li");if(!r)return;const{height:t}=r.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
